export const GetAllDoctors = async () => {
  const fakeDoctors: Doctor[] = [
    {
      id: 1,
      imgPath: "https://randomuser.me/api/portraits/lego/3.jpg",
      name: "Nguyễn Văn Dũng",
      address: "123, Lê Văn Việt, Tp. Thủ Đức",
      email: "nguyenvandung12@gmail.com",
      consultant: "Tư vấn Dinh dưỡng",
      socialNetwork: "Facebook",
      fee: 150000,
      phoneNumber: "01237123099",
    },
    {
      id: 2,
      imgPath: "https://randomuser.me/api/portraits/lego/3.jpg",
      name: "Lê Trung Thọ",
      address: "123, Lê Văn Việt, Tp. Thủ Đức",
      email: "nguyenvandung12@gmail.com",
      consultant: "Tư vấn Dinh dưỡng",
      socialNetwork: "Facebook",
      fee: 150000,
      phoneNumber: "08128241932",
    },
    {
      id: 3,
      imgPath: "https://randomuser.me/api/portraits/lego/3.jpg",
      name: "Lê Vũ Đình Duy",
      address: "123, Lê Văn Việt, Tp. Thủ Đức",
      email: "nguyenvandung12@gmail.com",
      consultant: "Tư vấn Dinh dưỡng",
      socialNetwork: "Facebook",
      fee: 150000,
      phoneNumber: "01237123099",
    },
    {
      id: 4,
      imgPath: "https://randomuser.me/api/portraits/lego/3.jpg",
      name: "Tống Ái Linh",
      address: "123, Lê Văn Việt, Tp. Thủ Đức",
      email: "nguyenvandung12@gmail.com",
      consultant: "Tư vấn Dinh dưỡng",
      socialNetwork: "Facebook",
      fee: 150000,
      phoneNumber: "08128241932",
    },
    {
      id: 5,
      imgPath: "https://randomuser.me/api/portraits/lego/3.jpg",
      name: "Tống Ái Linh",
      address: "123, Lê Văn Việt, Tp. Thủ Đức",
      email: "nguyenvandung12@gmail.com",
      consultant: "Tư vấn Dinh dưỡng",
      socialNetwork: "Facebook",
      fee: 150000,
      phoneNumber: "08128241932",
    },
    {
      id: 6,
      imgPath: "https://randomuser.me/api/portraits/lego/3.jpg",
      name: "Lê Vũ Đình Duy",
      address: "123, Lê Văn Việt, Tp. Thủ Đức",
      email: "nguyenvandung12@gmail.com",
      consultant: "Tư vấn Dinh dưỡng",
      socialNetwork: "Facebook",
      fee: 150000,
      phoneNumber: "01237123099",
    },
    {
      id: 7,
      imgPath: "https://randomuser.me/api/portraits/lego/3.jpg",
      name: "Lê Trung Thọ",
      address: "123, Lê Văn Việt, Tp. Thủ Đức",
      email: "nguyenvandung12@gmail.com",
      consultant: "Tư vấn Dinh dưỡng",
      socialNetwork: "Facebook",
      fee: 150000,
      phoneNumber: "08128241932",
    },
    {
      id: 8,
      imgPath: "https://randomuser.me/api/portraits/lego/3.jpg",
      name: "Nguyễn Văn Dũng",
      address: "123, Lê Văn Việt, Tp. Thủ Đức",
      email: "nguyenvandung12@gmail.com",
      consultant: "Tư vấn Dinh dưỡng",
      socialNetwork: "Facebook",
      fee: 150000,
      phoneNumber: "08128241932",
    },
  ];

  return fakeDoctors;
};
